import hashlib
import unicodedata

from typing import Any


class MediaIdentityService:
    """
    Builds deterministic identity values for Media records.

    record_key is generated by VV and must be stable
    across repeated runs for the same logical record.
    """

    @staticmethod
    def generate_record_key(
        source_config: dict[str, Any],
        record: dict[str, Any],
    ) -> str:
        identity_config = source_config.get("identity", {})
        record_key_config = identity_config.get("record_key", {})

        fields = record_key_config.get("fields", [])

        if not fields:
            raise ValueError(
                "No record_key fields configured for this media source."
            )

        values: list[str] = []
        record_values: list[str] = []
        hash_record_key = bool(
            record_key_config.get("hash", False)
        )

        for field in fields:
            # First try source-level config values
            if field in source_config:
                value = source_config[field]
            else:
                value = record.get(field)

            if not hash_record_key and (
                value is None
                or str(value).strip() == ""
            ):
                raise ValueError(
                    f"Missing value for record_key field: {field}"
                )

            normalized = unicodedata.normalize(
                "NFKC",
                "" if value is None else str(value),
            )
            normalized = " ".join(
                normalized.split()
            ).strip()

            if hash_record_key:
                normalized = normalized.casefold()

            values.append(normalized)

            if field not in source_config:
                record_values.append(normalized)

        if hash_record_key:
            if not any(record_values):
                raise ValueError(
                    "Record identity fields are empty."
                )

            return hashlib.sha256(
                "\x1f".join(values).encode("utf-8")
            ).hexdigest()

        return "|".join(values)

    @staticmethod
    def extract_external_id(
        source_config: dict[str, Any],
        record: dict[str, Any],
    ) -> str | None:
        """
        Return source-provided external id when available.
        It may legitimately be None.
        """

        identity_config = source_config.get("identity", {})
        external_id_config = identity_config.get("external_id", {})

        field = external_id_config.get("field")

        if not field:
            return None

        value = record.get(field)

        if value is None:
            return None

        value = str(value).strip()

        return value or None
